# CREATION D'UN NOTEBOOK DANS JUPYTER
BrainHack 14 mai au 1er juin 2018

Programme en Python pour la generation de donnees selon une distribution normale ou uniforme

Module 1 - Generation des donnees

In [61]:
# Module pour generer les variables t,u,v,w,x,y et z
# cognition = f(t,u,v,w,x,y,z) = 2.1*t/140 + 3.6*u/70 + 2.8*v/7 + 5*w/80 + 1.4*x/5 - 2.5*y/12 + 4*z/40
#   t = tasys=systolic blood pressure (moyenne=140, deviation standard=20)
#   u = tadia=diastolic blood pressure (moyenne=70, deviation standard=10)
#   v = hba1c=glycosylated Hb (moyenne=7, deviation standard=2)
#   w = age=age (moyenne=80, deviation standard=10)
#   x = ldl=LDL (moyenne=5, deviation standard=2)
#   y = edu=years of education (moyenne=12, deviation standard=2)
#   z = vs=VS (moyenne=40, deviation standard=20)


import numpy as np
import math


#
# entrez le nombre de participants (nb)
# deux versions: 3 premieres lignes pour l'entrer au clavier OU l'entrer dans le code directement
#v1-1 print('Entrez le nombre de participants: ')
#v1-2 input(nb_part)
#v1-3 nb = int(nb_part)
#OU

nb = 1000

a = np.zeros((nb, 1))
b = np.zeros((nb, 1))
c = np.zeros((nb, 1))
d = np.zeros((nb, 1))
e = np.zeros((nb, 1))
f = np.zeros((nb, 1))
g = np.zeros((nb, 1))


#
# TA systolique (tasys)

compteur = 0
while compteur < nb:
    a[compteur] = math.floor(np.random.normal(140.0, 20.0, 1))
    compteur+=1

tasys = a
#print(tasys)

print('moyenne TA systolique: ', np.mean(tasys))
print('deviation standard TA systolique: ', np.std(tasys))
print('')


#
# TA diastolique (tadia)
compteur = 0
while compteur < nb:
    b[compteur] = math.floor(np.random.normal(70, 10.0, 1))
    compteur+=1

tadia = b
#print(tadia)

print('moyenne TA diastolique: ', np.mean(tadia))
print('deviation standard TA diastolique: ', np.std(tadia))
print('')


#
# HbA1C (hba1c)
compteur = 0
while compteur < nb:
    c[compteur] = np.random.normal(7, 2, 1)
    compteur+=1

hba1c = c
#print(hba1c)

print('moyenne hemoglobine glyquee HbA1C: ', np.mean(hba1c))
print('deviation standard hemoglobine glyquee HbA1C: ', np.std(hba1c))
print('')


#
# Age (age)
compteur = 0
while compteur < nb:
    d[compteur] = math.floor(np.random.normal(80, 10.0, 1))
    compteur+=1

age = d
#print(age)

print('moyenne age: ', np.mean(age))
print('deviation standard age: ', np.mean(age))
print('')


#
# Cholesterol LDL (ldl)
compteur = 0
while compteur < nb:
    e[compteur] = np.random.normal(5, 2, 1)
    compteur+=1

ldl = e
#print(ldl)

print('moyenne cholesterol LDL:', np.mean(ldl))
print('deviation standard cholesterol LDL: ', np.std(ldl))
print('')


#
# Annees d'education (edu)
compteur = 0
while compteur < nb:
    f[compteur] = math.floor(np.random.normal(12, 2, 1))
    compteur+=1

edu = f
#print(edu)

print('moyenne education: ', np.mean(edu))
print('deviation standard education: ', np.std(edu))
print('')


#
# Vitesse de sedimentation/inflammation (vs)
compteur = 0
while compteur < nb:
    g[compteur] = math.floor(np.random.normal(40, 20, 1))
    if g[compteur]<0:
        g[compteur] = -g[compteur]
    else:
        g[compteur] = g[compteur]
    compteur+=1
    
vs = g
#print(vs)

print('moyenne vitesse de sedimentation: ', np.mean(vs))
print('deviation standard vitesse de sedimentation: ', np.std(vs))
print('')

print(tasys)
print(tadia)
print(hba1c)
print(age)
print(ldl)
print(edu)
print(vs)


moyenne TA systolique:  139.27
deviation standard TA systolique:  20.2387524319

moyenne TA diastolique:  69.628
deviation standard TA diastolique:  10.5071221559

moyenne hemoglobine glyquee HbA1C:  7.03868168965
deviation standard hemoglobine glyquee HbA1C:  2.03995703736

moyenne age:  79.368
deviation standard age:  79.368

moyenne cholesterol LDL: 5.05614362337
deviation standard cholesterol LDL:  1.92825452688

moyenne education:  11.481
deviation standard education:  2.00739607452

moyenne vitesse de sedimentation:  39.843
deviation standard vitesse de sedimentation:  18.5417461691

[[ 134.]
 [ 135.]
 [ 132.]
 [ 158.]
 [ 156.]
 [ 167.]
 [ 151.]
 [ 141.]
 [ 131.]
 [ 118.]
 [ 138.]
 [ 122.]
 [ 181.]
 [  94.]
 [ 135.]
 [ 125.]
 [ 129.]
 [ 112.]
 [ 107.]
 [ 153.]
 [ 141.]
 [ 136.]
 [ 155.]
 [ 172.]
 [ 118.]
 [ 144.]
 [ 100.]
 [ 125.]
 [ 159.]
 [ 126.]
 [ 153.]
 [ 142.]
 [ 141.]
 [ 145.]
 [ 114.]
 [ 134.]
 [ 148.]
 [ 123.]
 [ 143.]
 [ 115.]
 [ 156.]
 [ 130.]
 [ 110.]
 [ 150.]
 [ 110.

[[  31.]
 [  61.]
 [  63.]
 [  14.]
 [  36.]
 [  45.]
 [  49.]
 [  26.]
 [  49.]
 [  27.]
 [  55.]
 [  26.]
 [  49.]
 [  30.]
 [  71.]
 [  44.]
 [  44.]
 [  31.]
 [  35.]
 [  47.]
 [   1.]
 [  41.]
 [  23.]
 [   1.]
 [  46.]
 [  65.]
 [  28.]
 [  23.]
 [  50.]
 [  26.]
 [  29.]
 [  37.]
 [  35.]
 [  21.]
 [  12.]
 [  30.]
 [  20.]
 [  36.]
 [  32.]
 [  41.]
 [  24.]
 [  72.]
 [  60.]
 [  67.]
 [  18.]
 [  34.]
 [  47.]
 [  48.]
 [  66.]
 [  64.]
 [  12.]
 [  35.]
 [  27.]
 [  43.]
 [  34.]
 [  24.]
 [  14.]
 [  52.]
 [  52.]
 [  22.]
 [  66.]
 [  34.]
 [   9.]
 [  11.]
 [  24.]
 [  16.]
 [  18.]
 [  20.]
 [  30.]
 [   0.]
 [  55.]
 [  47.]
 [  45.]
 [  11.]
 [  36.]
 [  35.]
 [  41.]
 [  27.]
 [  41.]
 [  39.]
 [  25.]
 [  27.]
 [  29.]
 [  38.]
 [  39.]
 [  62.]
 [  33.]
 [  43.]
 [  64.]
 [  35.]
 [  42.]
 [  70.]
 [  77.]
 [  54.]
 [  19.]
 [  45.]
 [  58.]
 [  36.]
 [  13.]
 [  46.]
 [  47.]
 [  38.]
 [  36.]
 [  72.]
 [  44.]
 [   6.]
 [  49.]
 [   8.]
 [  60.]
 [  44.]
 [  54.]
 

# Calcul de la cognition selon la formule dans l'entete

In [62]:
#
# cognition (cog)
h = np.zeros((nb, 1))

compteur = 0
while compteur < nb:
    h[compteur] = - 2.1*(tasys[compteur]/110) - 3.6*(tadia[compteur]/60) - 2.8*(hba1c[compteur]/7) - 5*(age[compteur]/65) - 1.4*(ldl[compteur]/4) + 2.5*(edu[compteur]/10) - 4*(vs[compteur]/30)
    compteur+=1

cog = h
#print(cog)

print('moyenne cognition: ', np.mean(cog))
print('deviation standard cognition: ', np.std(cog))
print('')

type(cog)

compteur = 0
while compteur < nb:
    cog[compteur] = np.round(cog[compteur], 2)
    compteur+=1

print(cog)

moyenne cognition:  -19.9689746224
deviation standard cognition:  2.90619652481

[[-21.96]
 [-23.34]
 [-22.94]
 [-16.11]
 [-20.04]
 [-20.87]
 [-22.14]
 [-17.01]
 [-20.53]
 [-20.54]
 [-21.91]
 [-14.95]
 [-22.33]
 [-18.27]
 [-23.89]
 [-18.13]
 [-19.93]
 [-18.05]
 [-20.18]
 [-20.76]
 [-14.25]
 [-18.09]
 [-18.22]
 [-14.38]
 [-20.93]
 [-21.64]
 [-19.57]
 [-17.19]
 [-19.87]
 [-18.29]
 [-19.89]
 [-19.12]
 [-16.39]
 [-15.31]
 [-16.45]
 [-18.11]
 [-20.12]
 [-19.02]
 [-20.09]
 [-21.04]
 [-20.23]
 [-22.85]
 [-20.34]
 [-23.6 ]
 [-15.85]
 [-20.09]
 [-21.41]
 [-21.9 ]
 [-23.47]
 [-23.74]
 [-15.41]
 [-17.26]
 [-16.84]
 [-20.85]
 [-22.78]
 [-16.92]
 [-12.3 ]
 [-24.23]
 [-20.72]
 [-17.51]
 [-24.21]
 [-18.82]
 [-13.99]
 [-18.12]
 [-16.5 ]
 [-17.1 ]
 [-19.36]
 [-14.93]
 [-18.24]
 [-16.76]
 [-22.65]
 [-20.84]
 [-21.12]
 [-16.25]
 [-19.98]
 [-20.43]
 [-19.27]
 [-18.63]
 [-21.45]
 [-17.68]
 [-18.49]
 [-16.29]
 [-17.29]
 [-19.91]
 [-25.49]
 [-23.85]
 [-17.61]
 [-19.37]
 [-22.11]
 [-19.11]
 [-19.66]
 [-23.27]

# Creation du fichier contenant les donnees en format csv

In [63]:
import pandas as pd


#
# Inclusion des donnees dans un tableau nomme data_table
# Creation du fichier bh_data_table.csv


#
# reinitialise le tableau met les donnees aleatoires calculees dans les cellules precedentes

data_list = list()

compteur_participant = 0
while compteur_participant < nb:
    participant_data = list()
    participant_data.append(tasys[compteur_participant])
    participant_data.append(tadia[compteur_participant])
    participant_data.append(hba1c[compteur_participant])
    participant_data.append(age[compteur_participant])
    participant_data.append(ldl[compteur_participant])
    participant_data.append(edu[compteur_participant])
    participant_data.append(vs[compteur_participant])
    participant_data.append(cog[compteur_participant])
    data_list.append(participant_data)
    compteur_participant+=1

          
# 
# Creation du fichier cvs a partir de Pandas
data_list_entete = ['tasys','tadia','hba1c','age','ldl','edu','vs','cog']
bh_data_table = pd.DataFrame(data=data_list)
print(bh_data_table)
bh_data_table.to_csv('bh_data_table.csv', header=data_list_entete)



           0       1                2       3                 4       5  \
0    [134.0]  [85.0]  [8.43159799874]  [99.0]   [6.24129651069]  [12.0]   
1    [135.0]  [66.0]  [5.78481860794]  [78.0]   [8.14933987778]  [10.0]   
2    [132.0]  [70.0]  [6.53653089143]  [87.0]   [4.33594213554]  [12.0]   
3    [158.0]  [63.0]  [6.29093596455]  [85.0]   [4.67968146376]  [13.0]   
4    [156.0]  [75.0]  [7.12659493215]  [77.0]   [5.66829393909]  [12.0]   
5    [167.0]  [68.0]  [8.21256297559]  [80.0]  [0.475599522641]   [8.0]   
6    [151.0]  [71.0]  [7.25790559052]  [78.0]   [7.31543595551]  [12.0]   
7    [141.0]  [67.0]  [7.80848504462]  [69.0]   [6.86570482106]  [16.0]   
8    [131.0]  [59.0]  [7.23146367582]  [66.0]   [5.67432251855]   [8.0]   
9    [118.0]  [64.0]   [9.5870882759]  [96.0]   [6.08963483786]  [10.0]   
10   [138.0]  [88.0]  [5.49592333923]  [78.0]   [4.18470517684]  [12.0]   
11   [122.0]  [52.0]  [5.60639817367]  [76.0]   [3.40725381128]  [13.0]   
12   [181.0]  [87.0]  [9.